/*
-- Query: SELECT * FROM spr.spr_model
LIMIT 0, 1000

-- Date: 2022-03-30 14:46
*/
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.Group');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.GroupEmployee');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.GroupOrganization');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.GroupPositionLevel');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.GroupRelation');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.GroupRole');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.GroupSysrole');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.group.GroupUser');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.Employee');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.EmployeeOrganizationLevel');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.EmployeeOrganizationRole');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.EmployeeRelation');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.EmployeeUser');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.Organization');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.OrganizationGroup');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.OrganizationPositionLevel');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.OrganizationPositionLevelRelation');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.OrganizationRelation');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.OrganizationRole');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.OrganizationRoleRelation');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.PositionLevel');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.organization.Role');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.Menu');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.Model');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.ModelAttribute');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.Scope');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.SparrowApi');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.SparrowFile');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.Sysrole');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.SysroleApi');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.SysroleMenu');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.SysroleScope');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.UserMenu');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.UserScope');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.resource.UserSysrole');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.token.DataPermissionToken');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.token.FieldPermissionToken');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.token.SparrowEmployeeToken');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'cn.sparrow.permission.model.token.SparrowPermissionToken');
INSERT INTO spr_model (`name`,`created_by`,`created_date`,`modified_by`,`modified_date`,`is_system`,`remark`,`permission_token_id`,`data_permission_token_id`,`id`) VALUES (NULL,NULL,'2022-03-30 04:42:04',NULL,'2022-03-30 04:42:04','1',NULL,NULL,NULL,'org.hibernate.envers.DefaultRevisionEntity');
